apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiers-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiers
  template:
    metadata:
      labels:
        app: tiers
    spec:
      containers:
        - name: tiers
          image: viktordojchinovski/tiers
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "nats://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: synergeticpages
            - name: MONGO_URI
              value: "mongodb://tiers-mongo-srv:27017/tiers"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tiers-srv
spec:
  selector:
    app: tiers
  ports:
    - name: tiers
      protocol: TCP
      port: 3000
      targetPort: 3000
