name: tests-subscrpitions

on:
  pull_request:
    paths:
      - "subscriptions/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd subscriptions && npm install && npm run test:ci
