name: tests-tiers

on:
  pull_request:
    paths:
      - "tiers/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tiers && npm install && npm run test:ci
